# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opencast.ui'
#
# Created: Mon Apr 27 03:14:10 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(550, 217)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("res/images.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 551, 161))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(50, 50, 67, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.strstart = QtGui.QPushButton(self.tab)
        self.strstart.setGeometry(QtCore.QRect(170, 50, 71, 21))
        self.strstart.setObjectName(_fromUtf8("strstart"))
        self.strstop = QtGui.QPushButton(self.tab)
        self.strstop.setGeometry(QtCore.QRect(270, 50, 71, 21))
        self.strstop.setObjectName(_fromUtf8("strstop"))
        self.strprev = QtGui.QPushButton(self.tab)
        self.strprev.setGeometry(QtCore.QRect(400, 50, 71, 21))
        self.strprev.setObjectName(_fromUtf8("strprev"))
        self.strlabl = QtGui.QLabel(self.tab)
        self.strlabl.setGeometry(QtCore.QRect(0, 100, 301, 21))
        self.strlabl.setScaledContents(False)
        self.strlabl.setObjectName(_fromUtf8("strlabl"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.recstop = QtGui.QPushButton(self.tab_2)
        self.recstop.setGeometry(QtCore.QRect(270, 50, 71, 21))
        self.recstop.setObjectName(_fromUtf8("recstop"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 67, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.recstart = QtGui.QPushButton(self.tab_2)
        self.recstart.setGeometry(QtCore.QRect(170, 50, 71, 21))
        self.recstart.setObjectName(_fromUtf8("recstart"))
        self.reclabl = QtGui.QLabel(self.tab_2)
        self.reclabl.setGeometry(QtCore.QRect(0, 100, 161, 21))
        self.reclabl.setObjectName(_fromUtf8("reclabl"))
        self.gdes = QtGui.QCheckBox(self.tab_2)
        self.gdes.setGeometry(QtCore.QRect(50, 10, 191, 26))
        self.gdes.setChecked(True)
        self.gdes.setAutoExclusive(True)
        self.gdes.setObjectName(_fromUtf8("gdes"))
        self.gwin = QtGui.QCheckBox(self.tab_2)
        self.gwin.setGeometry(QtCore.QRect(270, 10, 191, 26))
        self.gwin.setAutoExclusive(True)
        self.gwin.setObjectName(_fromUtf8("gwin"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Open Cast", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Stream", None, QtGui.QApplication.UnicodeUTF8))
        self.strstart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.strstop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.strprev.setText(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.strlabl.setText(QtGui.QApplication.translate("MainWindow", "Streaming", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Stream", None, QtGui.QApplication.UnicodeUTF8))
        self.recstop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.recstart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.reclabl.setText(QtGui.QApplication.translate("MainWindow", "Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.gdes.setText(QtGui.QApplication.translate("MainWindow", "Grab the whole desktop", None, QtGui.QApplication.UnicodeUTF8))
        self.gwin.setText(QtGui.QApplication.translate("MainWindow", "Capture window", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Local Record", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

